server:
  port: 18000
spring:
  application:
    name: "eureka-server"
eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    hostname: "eurekaServer18000"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/"
  server:
    enable-self-preservation: false